package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type codexProjectDocSpec struct {
	templateRel string
	destRel     string
	label       string
	managedFn   func(string) bool
}

func syncCodexProjectDocs(hubSystem, repoDir string) ([]map[string]interface{}, int, int, []string) {
	specs := []codexProjectDocSpec{
		{
			templateRel: filepath.Join("templates", "agents-md-template.md"),
			destRel:     "AGENTS.md",
			label:       "AGENTS.md",
			managedFn:   isAetherManagedAgentsDoc,
		},
		{
			templateRel: filepath.Join("templates", "codex-md-template.md"),
			destRel:     filepath.Join(".codex", "CODEX.md"),
			label:       ".codex/CODEX.md",
			managedFn:   isAetherManagedCodexDoc,
		},
	}

	results := make([]map[string]interface{}, 0, len(specs))
	totalCopied := 0
	totalSkipped := 0
	var errs []string

	for _, spec := range specs {
		entry, copied, skipped, err := syncManagedProjectDoc(hubSystem, repoDir, spec)
		results = append(results, entry)
		totalCopied += copied
		totalSkipped += skipped
		if err != nil {
			errs = append(errs, err.Error())
		}
	}

	return results, totalCopied, totalSkipped, errs
}

func syncManagedProjectDoc(hubSystem, repoDir string, spec codexProjectDocSpec) (map[string]interface{}, int, int, error) {
	entry := map[string]interface{}{"label": spec.label}
	templatePath := filepath.Join(hubSystem, spec.templateRel)
	destPath := filepath.Join(repoDir, spec.destRel)

	templateBytes, err := os.ReadFile(templatePath)
	if err != nil {
		if os.IsNotExist(err) {
			entry["skipped"] = 1
			entry["reason"] = "template missing"
			return entry, 0, 1, nil
		}
		entry["errors"] = []string{err.Error()}
		return entry, 0, 0, fmt.Errorf("%s template: %w", spec.label, err)
	}

	rendered := renderCodexProjectDocTemplate(string(templateBytes))

	existingBytes, err := os.ReadFile(destPath)
	if err == nil {
		existing := string(existingBytes)
		if existing == rendered {
			entry["skipped"] = 1
			entry["reason"] = "unchanged"
			return entry, 0, 1, nil
		}
		if !spec.managedFn(existing) {
			entry["skipped"] = 1
			entry["reason"] = "preserved local custom file"
			entry["preserved_local"] = true
			return entry, 0, 1, nil
		}
	} else if !os.IsNotExist(err) {
		entry["errors"] = []string{err.Error()}
		return entry, 0, 0, fmt.Errorf("read %s: %w", destPath, err)
	}

	if err := os.MkdirAll(filepath.Dir(destPath), 0755); err != nil {
		entry["errors"] = []string{err.Error()}
		return entry, 0, 0, fmt.Errorf("mkdir %s: %w", filepath.Dir(destPath), err)
	}
	if err := os.WriteFile(destPath, []byte(rendered), 0644); err != nil {
		entry["errors"] = []string{err.Error()}
		return entry, 0, 0, fmt.Errorf("write %s: %w", destPath, err)
	}

	entry["copied"] = 1
	return entry, 1, 0, nil
}

func renderCodexProjectDocTemplate(template string) string {
	template = strings.ReplaceAll(template, "{COLONY_NAME}", "")
	template = strings.ReplaceAll(template, "{COLONY_GOAL}", "")
	return template
}

func isAetherManagedAgentsDoc(content string) bool {
	return strings.Contains(content, "Aether Colony -- Codex CLI Instructions") ||
		strings.Contains(content, "Generated by Aether setup") ||
		strings.Contains(content, "All colony operations use the `aether` CLI binary directly")
}

func isAetherManagedCodexDoc(content string) bool {
	return strings.Contains(content, "Aether Codex Workflow Guide") ||
		strings.Contains(content, "Generated by Aether setup") ||
		strings.Contains(content, "This repo is Aether-enabled for Codex CLI")
}
