package cmd

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// Exercise registered setup with real published templates and installed support.
// Registered update's combined payload/doc receipt is covered by Plan 06.
func runAntGuidanceSetup(t *testing.T, home, repo string) []map[string]interface{} {
	t.Helper()
	saveGlobals(t)
	resetRootCmd(t)
	t.Setenv("AETHER_HUB_DIR", "")
	t.Setenv("AETHER_OUTPUT_MODE", "json")
	var output bytes.Buffer
	stdout, stderr = &output, &output
	rootCmd.SetArgs([]string{"setup", "--repo-dir", repo, "--home-dir", home})
	if err := rootCmd.Execute(); err != nil {
		t.Fatalf("setup: %v: %s", err, output.String())
	}
	var envelope struct {
		OK     bool `json:"ok"`
		Result struct {
			Details []map[string]interface{} `json:"details"`
		} `json:"result"`
	}
	if err := json.Unmarshal(output.Bytes(), &envelope); err != nil || !envelope.OK {
		t.Fatalf("setup receipt: %v: %s", err, output.String())
	}
	return envelope.Result.Details
}

func TestCodexAntSkillManagedGuidance(t *testing.T) {
	home, repo := t.TempDir(), t.TempDir()
	if ok, output := runAntSkillInstall(t, home); !ok {
		t.Fatalf("install: %s", output)
	}
	assertCodexSkillFixtureInstalled(t, antSkillSourceRoot(t), home)
	docs := map[string]string{
		"AGENTS.md":       "Aether Colony -- Codex CLI Instructions",
		".codex/CODEX.md": "Aether Codex Workflow Guide",
	}
	publicName := regexp.MustCompile(`\$ant-[a-z]+(?:-[a-z]+)*`)
	check := func(t *testing.T) {
		t.Helper()
		for rel, sentinel := range docs {
			raw, err := os.ReadFile(filepath.Join(repo, rel))
			if err != nil {
				t.Fatal(err)
			}
			content := string(raw)
			prose := strings.Join(strings.Fields(content), " ")
			names := map[string]bool{}
			for _, name := range publicName.FindAllString(content, -1) {
				names[strings.TrimPrefix(name, "$")] = true
			}
			var got []string
			for name := range names {
				got = append(got, name)
			}
			sort.Strings(got)
			if !reflect.DeepEqual(got, expectedAntSkills) {
				t.Errorf("%s public names = %v, want exactly %v", rel, got, expectedAntSkills)
			}
			for _, required := range []string{sentinel, "Generated by Aether setup", "aether --help", "aether command-guide <command> --platform codex", "raw", "exact", "no-interview", "no-orchestration", "passthrough", "fresh Codex session", "~/.codex/skills/aether/", "private support", "remaining 55", "native-worker parity"} {
				if !strings.Contains(prose, required) {
					t.Errorf("%s missing guidance %q", rel, required)
				}
			}
			for _, support := range []string{"aether-colony-creation", "aether-colony-research", "aether-colony-build-cycle"} {
				if !strings.Contains(content, "support/"+support+".md") {
					t.Errorf("%s missing private support path %s", rel, support)
				}
			}
			for _, obsolete := range []string{"{COLONY_NAME}", "{COLONY_GOAL}", "Codex CLI does not support slash commands", "$aether-", "Old managed guidance"} {
				if strings.Contains(content, obsolete) {
					t.Errorf("%s retains obsolete/unrendered guidance %q", rel, obsolete)
				}
			}
		}
	}
	t.Run("setup", func(t *testing.T) {
		runAntGuidanceSetup(t, home, repo)
		check(t)
	})
	t.Run("refresh", func(t *testing.T) {
		for rel, sentinel := range docs {
			writeMaintenanceMutation199File(t, filepath.Join(repo, rel), []byte("# "+sentinel+"\nOld managed guidance\n"))
		}
		details, _, _, errs := syncProjectDocs(filepath.Join(home, ".aether", "system"), repo)
		if len(errs) != 0 || !assetCopied(details, "AGENTS.md") || !assetCopied(details, ".codex/CODEX.md") {
			t.Fatalf("refresh did not replace both managed docs: %v %v", details, errs)
		}
		check(t)
	})
	t.Run("unchanged", func(t *testing.T) {
		details, copied, _, errs := syncProjectDocs(filepath.Join(home, ".aether", "system"), repo)
		if len(errs) != 0 || copied != 0 || platformRestartMessage(platformRestartTargets(details)) != "" {
			t.Fatalf("unchanged guidance must be quiet: %v %v", details, errs)
		}
		check(t)
	})
}

func TestCodexAntSkillCustomGuidancePreserved(t *testing.T) {
	home, repo := t.TempDir(), t.TempDir()
	if ok, output := runAntSkillInstall(t, home); !ok {
		t.Fatalf("install: %s", output)
	}
	custom := map[string][]byte{
		"AGENTS.md":       []byte("# Owner instructions\r\nKeep my $ant-plan notes.\r\n"),
		".codex/CODEX.md": []byte("# Local guide\nOwner says: café 🐜\n"),
	}
	for rel, data := range custom {
		writeMaintenanceMutation199File(t, filepath.Join(repo, rel), data)
	}
	check := func(t *testing.T, details []map[string]interface{}) {
		t.Helper()
		for rel, want := range custom {
			got, err := os.ReadFile(filepath.Join(repo, rel))
			if err != nil || !bytes.Equal(got, want) {
				t.Fatalf("custom %s changed: %v", rel, err)
			}
			found := false
			for _, entry := range details {
				if entry["label"] == rel && entry["preserved_local"] == true && entry["reason"] == "preserved local custom file" && intValue(entry["skipped"]) == 1 && intValue(entry["copied"]) == 0 {
					found = true
				}
			}
			if !found {
				t.Errorf("missing custom preservation receipt for %s: %v", rel, details)
			}
		}
	}
	t.Run("setup", func(t *testing.T) { check(t, runAntGuidanceSetup(t, home, repo)) })
	t.Run("refresh", func(t *testing.T) {
		details, copied, _, errs := syncProjectDocs(filepath.Join(home, ".aether", "system"), repo)
		if len(errs) != 0 || copied != 0 {
			t.Fatalf("custom refresh: %v %v", details, errs)
		}
		check(t, details)
	})
}

func TestCodexAntSkillRestartNotice(t *testing.T) {
	for _, tc := range []struct {
		name    string
		details []map[string]interface{}
		want    int
	}{
		{"copied", []map[string]interface{}{{"label": "Skills (codex shims)", "copied": 9}}, 1},
		{"removal-only", []map[string]interface{}{{"label": "Skills (codex shims)", "removed": 14}}, 1},
		{"unchanged", []map[string]interface{}{{"label": "Skills (codex shims)", "skipped": 12}}, 0},
		{"deduplicated", []map[string]interface{}{{"label": "Skills (codex shims)", "copied": 9}, {"label": "Skills (codex shims)", "removed": 14}, {"label": "AGENTS.md", "copied": 1}, {"label": "Agents (codex)", "copied": 27}}, 1},
		{"unrelated-removal", []map[string]interface{}{{"label": "Rules", "removed": 1}}, 0},
		{"preserved-custom", []map[string]interface{}{{"label": "AGENTS.md", "skipped": 1, "preserved_local": true}}, 0},
		{"mixed-platforms", []map[string]interface{}{{"label": "Skills (codex shims)", "removed": float64(1)}, {"label": "Agents (opencode)", "copied": 1}}, 1},
	} {
		t.Run(tc.name, func(t *testing.T) {
			targets := platformRestartTargets(tc.details)
			message := platformRestartMessage(targets)
			if got := strings.Count(message, "Close this Codex chat and start a new one"); got != tc.want {
				t.Errorf("Codex notices = %d, want %d: %q", got, tc.want, message)
			}
			if tc.want == 0 && message != "" {
				t.Errorf("unchanged/preserved assets must be quiet: %q", message)
			}
			if tc.want == 1 && strings.Count(message, "Codex skill shims") != 1 {
				t.Errorf("skill change must appear once in notice: %q", message)
			}
			if tc.name == "mixed-platforms" && strings.Count(message, "Restart your OpenCode session") != 1 {
				t.Errorf("lost OpenCode notice: %q", message)
			}
		})
	}
}

func TestIsAetherManagedOpenCodeDoc(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{
			name:    "managed with sentinel",
			content: "# Colony\n\n> Aether Colony -- OpenCode Instructions\n\nSome content",
			want:    true,
		},
		{
			name:    "managed with generated marker",
			content: "# Colony\n\n*Generated by Aether setup. Customize this file for your project.*",
			want:    true,
		},
		{
			name:    "managed with enabled marker",
			content: "# Colony\n\nThis repo is Aether-enabled for OpenCode\n",
			want:    true,
		},
		{
			name:    "not managed — custom content",
			content: "# My Project\n\nCustom OpenCode instructions\n",
			want:    false,
		},
		{
			name:    "not managed — Codex doc",
			content: "# Colony\n\n> Aether Colony -- Codex CLI Instructions\n",
			want:    false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := isAetherManagedOpenCodeDoc(tt.content); got != tt.want {
				t.Errorf("isAetherManagedOpenCodeDoc() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestPlatformRestartTargetsIncludesOpenCode(t *testing.T) {
	details := []map[string]interface{}{
		{"label": "AGENTS.md", "copied": 1},
		{"label": ".codex/CODEX.md", "copied": 1},
		{"label": ".opencode/OPENCODE.md", "copied": 1},
	}
	targets := platformRestartTargets(details)

	foundAGENTS := false
	foundOpenCode := false
	for _, t := range targets {
		if t == "AGENTS.md" {
			foundAGENTS = true
		}
		if t == ".opencode/OPENCODE.md" {
			foundOpenCode = true
		}
	}
	if !foundAGENTS {
		t.Error("expected AGENTS.md in restart targets")
	}
	if !foundOpenCode {
		t.Error("expected .opencode/OPENCODE.md in restart targets")
	}
}

func TestPlatformRestartMessageDualPlatform(t *testing.T) {
	targets := []string{"AGENTS.md", ".codex/CODEX.md", ".opencode/OPENCODE.md"}
	msg := platformRestartMessage(targets)

	if msg == "" {
		t.Fatal("expected non-empty restart message for dual-platform targets")
	}
	codexFound := false
	opencodeFound := false
	if containsStr(msg, "Close this Codex chat") {
		codexFound = true
	}
	if containsStr(msg, "Restart your OpenCode session") {
		opencodeFound = true
	}
	if !codexFound {
		t.Error("expected Codex restart guidance in dual-platform message")
	}
	if !opencodeFound {
		t.Error("expected OpenCode restart guidance in dual-platform message")
	}
}

func TestPlatformRestartMessageOpenCodeOnly(t *testing.T) {
	targets := []string{".opencode/OPENCODE.md", "OpenCode agents"}
	msg := platformRestartMessage(targets)

	if msg == "" {
		t.Fatal("expected non-empty restart message for OpenCode-only targets")
	}
	if containsStr(msg, "Close this Codex chat") {
		t.Error("did not expect Codex guidance for OpenCode-only targets")
	}
	if !containsStr(msg, "Restart your OpenCode session") {
		t.Error("expected OpenCode restart guidance")
	}
}

func TestSyncProjectDocsGeneratesOpenCodeMD(t *testing.T) {
	hubDir := t.TempDir()
	repoDir := t.TempDir()

	// Create hub template
	templatesDir := filepath.Join(hubDir, "templates")
	if err := os.MkdirAll(templatesDir, 0755); err != nil {
		t.Fatal(err)
	}
	opencodeTemplate := "# {COLONY_NAME}\n\n> Aether Colony -- OpenCode Instructions\n\nColony goal: {COLONY_GOAL}\n\n*Generated by Aether setup. Customize this file for your project.*\n"
	if err := os.WriteFile(filepath.Join(templatesDir, "opencode-md-template.md"), []byte(opencodeTemplate), 0644); err != nil {
		t.Fatal(err)
	}

	results, copied, _, _ := syncProjectDocs(hubDir, repoDir)

	if copied == 0 {
		t.Fatal("expected at least one file to be copied")
	}

	dest := filepath.Join(repoDir, ".opencode", "OPENCODE.md")
	content, err := os.ReadFile(dest)
	if err != nil {
		t.Fatalf("OpenCode OPENCODE.md was not created: %v", err)
	}

	result := string(content)
	if containsStr(result, "{COLONY_NAME}") {
		t.Error("expected {COLONY_NAME} to be replaced")
	}
	if containsStr(result, "{COLONY_GOAL}") {
		t.Error("expected {COLONY_GOAL} to be replaced")
	}
	if !containsStr(result, "Aether Colony -- OpenCode Instructions") {
		t.Error("expected sentinel in generated file")
	}

	// Verify the result entry
	found := false
	for _, entry := range results {
		if entry["label"] == ".opencode/OPENCODE.md" {
			found = true
			if entry["copied"] != 1 {
				t.Errorf("expected copied=1, got %v", entry["copied"])
			}
		}
	}
	if !found {
		t.Error("expected .opencode/OPENCODE.md entry in results")
	}
}

func TestSyncProjectDocsPreservesCustomOpenCodeMD(t *testing.T) {
	hubDir := t.TempDir()
	repoDir := t.TempDir()

	// Create hub template
	templatesDir := filepath.Join(hubDir, "templates")
	if err := os.MkdirAll(templatesDir, 0755); err != nil {
		t.Fatal(err)
	}
	opencodeTemplate := "# Colony\n\n> Aether Colony -- OpenCode Instructions\n\nNew template content.\n"
	if err := os.WriteFile(filepath.Join(templatesDir, "opencode-md-template.md"), []byte(opencodeTemplate), 0644); err != nil {
		t.Fatal(err)
	}

	// Pre-create custom OPENCODE.md (NOT managed by Aether)
	customContent := "# My Project\n\nCustom OpenCode instructions that should be preserved.\n"
	if err := os.MkdirAll(filepath.Join(repoDir, ".opencode"), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(repoDir, ".opencode", "OPENCODE.md"), []byte(customContent), 0644); err != nil {
		t.Fatal(err)
	}

	_, _, skipped, _ := syncProjectDocs(hubDir, repoDir)
	if skipped == 0 {
		t.Error("expected at least one file to be skipped")
	}

	// Custom content should be preserved
	content, err := os.ReadFile(filepath.Join(repoDir, ".opencode", "OPENCODE.md"))
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != customContent {
		t.Errorf("custom OPENCODE.md was overwritten\ngot:  %s\nwant: %s", string(content), customContent)
	}
}

func TestSyncProjectDocsRefreshesManagedOpenCodeMD(t *testing.T) {
	hubDir := t.TempDir()
	repoDir := t.TempDir()

	// Create hub template
	templatesDir := filepath.Join(hubDir, "templates")
	if err := os.MkdirAll(templatesDir, 0755); err != nil {
		t.Fatal(err)
	}
	newTemplate := "# Colony\n\n> Aether Colony -- OpenCode Instructions\n\nUpdated template content.\n\n*Generated by Aether setup. Customize this file for your project.*\n"
	if err := os.WriteFile(filepath.Join(templatesDir, "opencode-md-template.md"), []byte(newTemplate), 0644); err != nil {
		t.Fatal(err)
	}

	// Pre-create managed (Aether-owned) OPENCODE.md
	oldContent := "# Colony\n\n> Aether Colony -- OpenCode Instructions\n\nOld content.\n\n*Generated by Aether setup. Customize this file for your project.*\n"
	if err := os.MkdirAll(filepath.Join(repoDir, ".opencode"), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(repoDir, ".opencode", "OPENCODE.md"), []byte(oldContent), 0644); err != nil {
		t.Fatal(err)
	}

	_, copied, _, _ := syncProjectDocs(hubDir, repoDir)

	if copied == 0 {
		t.Fatal("expected at least one file to be copied (refreshed)")
	}

	// Verify file was updated
	content, err := os.ReadFile(filepath.Join(repoDir, ".opencode", "OPENCODE.md"))
	if err != nil {
		t.Fatal(err)
	}
	if string(content) == oldContent {
		t.Error("managed OPENCODE.md should have been refreshed but was not")
	}
	if !containsStr(string(content), "Updated template content") {
		t.Errorf("expected updated content in OPENCODE.md, got:\n%s", string(content))
	}
}
