package cmd

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"

	invopopjsonschema "github.com/invopop/jsonschema"
	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"
	"github.com/spf13/cobra"
	"golang.org/x/text/language"
	"golang.org/x/text/message"
)

// completionPacketSchemaRel is the repo-relative path where the generated
// completion-packet JSON Schema is committed.
const completionPacketSchemaRel = ".aether/schemas/completion-packet.schema.json"

// completionPacketSchemaID is the $id assigned to the generated schema.
const completionPacketSchemaID = "https://aether.dev/schemas/completion-packet.schema.json"

// completionPacketSchemaVersion pins the generated schema to JSON Schema
// draft 2020-12. This is also invopop/jsonschema's default, but is set
// explicitly here because determinism of the generated output is a hard
// requirement (cmd/contract_schema_test.go byte-compares it).
const completionPacketSchemaVersion = "https://json-schema.org/draft/2020-12/schema"

// contractViolation is the shared per-field violation shape emitted by
// completion-packet structural validation. It rides the existing
// outputError `details` payload (cmd/helpers.go) and is consumed by plans
// 02 and 03 to report every violation in a submitted packet at once,
// instead of one rejection per round-trip.
type contractViolation struct {
	Worker  string `json:"worker,omitempty"`
	Field   string `json:"field"`
	Value   string `json:"value,omitempty"`
	Rule    string `json:"rule"`
	Message string `json:"message"`
}

// violationPrinter renders ErrorKind messages in English. jsonschema's own
// default printer is unexported, so completion-packet validation carries
// its own.
var violationPrinter = message.NewPrinter(language.English)

// generateCompletionPacketSchemaBytes reflects codexExternalBuildCompletion
// (which transitively pulls in codexBuildManifest, codexBuildDispatch,
// codexExternalBuildWorkerResult, codexBuildClaims, and codex.WorkerHandoff)
// into a JSON Schema draft 2020-12 document. Output is marshaled with
// two-space indentation and a single trailing newline so it is
// byte-deterministic across runs — cmd/contract_schema_test.go relies on
// that determinism to detect drift between the Go structs and the
// committed schema file.
func generateCompletionPacketSchemaBytes() ([]byte, error) {
	reflector := &invopopjsonschema.Reflector{}
	schema := reflector.Reflect(&codexExternalBuildCompletion{})
	if schema == nil {
		return nil, fmt.Errorf("reflecting codexExternalBuildCompletion produced a nil schema")
	}

	schema.Version = completionPacketSchemaVersion
	schema.ID = invopopjsonschema.ID(completionPacketSchemaID)

	buf, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal generated completion-packet schema: %w", err)
	}
	buf = append(buf, '\n')
	return buf, nil
}

// compiledCompletionPacketSchemaState holds the lazily-compiled schema used
// for structural validation. It is compiled once from the in-memory
// generated bytes — never from the on-disk committed file — so an edited
// copy of .aether/schemas/completion-packet.schema.json cannot weaken
// runtime validation (T-163.1-01).
var (
	compiledCompletionPacketSchemaOnce sync.Once
	compiledCompletionPacketSchemaVal  *jsonschema.Schema
	compiledCompletionPacketSchemaErr  error
)

// compiledCompletionPacketSchema returns the compiled santhosh-tekuri
// validator for the completion-packet schema, compiling it exactly once
// per process from generateCompletionPacketSchemaBytes.
func compiledCompletionPacketSchema() (*jsonschema.Schema, error) {
	compiledCompletionPacketSchemaOnce.Do(func() {
		raw, err := generateCompletionPacketSchemaBytes()
		if err != nil {
			compiledCompletionPacketSchemaErr = fmt.Errorf("generate completion-packet schema: %w", err)
			return
		}

		doc, err := jsonschema.UnmarshalJSON(bytes.NewReader(raw))
		if err != nil {
			compiledCompletionPacketSchemaErr = fmt.Errorf("parse generated completion-packet schema: %w", err)
			return
		}

		compiler := jsonschema.NewCompiler()
		if err := compiler.AddResource(completionPacketSchemaID, doc); err != nil {
			compiledCompletionPacketSchemaErr = fmt.Errorf("register completion-packet schema resource: %w", err)
			return
		}

		compiled, err := compiler.Compile(completionPacketSchemaID)
		if err != nil {
			compiledCompletionPacketSchemaErr = fmt.Errorf("compile completion-packet schema: %w", err)
			return
		}

		compiledCompletionPacketSchemaVal = compiled
	})
	return compiledCompletionPacketSchemaVal, compiledCompletionPacketSchemaErr
}

// validateCompletionPacketStructure validates raw (a decoded JSON value —
// typically map[string]any from encoding/json.Unmarshal) against the
// compiled completion-packet schema and returns one contractViolation per
// leaf failure. A nil/empty return means raw is structurally valid.
func validateCompletionPacketStructure(raw any) []contractViolation {
	schema, err := compiledCompletionPacketSchema()
	if err != nil {
		return []contractViolation{{
			Field:   "",
			Rule:    "schema-compile",
			Message: fmt.Sprintf("completion-packet schema failed to compile: %v", err),
		}}
	}

	validateErr := schema.Validate(raw)
	if validateErr == nil {
		return nil
	}

	var verr *jsonschema.ValidationError
	if !errors.As(validateErr, &verr) {
		return []contractViolation{{
			Field:   "",
			Rule:    "schema-validate",
			Message: validateErr.Error(),
		}}
	}

	var violations []contractViolation
	var walk func(node *jsonschema.ValidationError)
	walk = func(node *jsonschema.ValidationError) {
		if node == nil {
			return
		}
		if len(node.Causes) == 0 {
			violations = append(violations, newContractViolation(node, raw))
			return
		}
		for _, cause := range node.Causes {
			walk(cause)
		}
	}
	walk(verr)

	return violations
}

// newContractViolation builds a single contractViolation from a leaf
// *jsonschema.ValidationError (a node with no further Causes).
func newContractViolation(node *jsonschema.ValidationError, raw any) contractViolation {
	field := jsonPointerFromSegments(node.InstanceLocation)

	rule := ""
	if node.ErrorKind != nil {
		if path := node.ErrorKind.KeywordPath(); len(path) > 0 {
			rule = path[len(path)-1]
		}
	}

	message := ""
	if node.ErrorKind != nil {
		message = node.ErrorKind.LocalizedString(violationPrinter)
	}

	return contractViolation{
		Worker:  resolveContractViolationWorker(raw, node.InstanceLocation),
		Field:   field,
		Rule:    rule,
		Message: message,
	}
}

// jsonPointerFromSegments renders instance-location segments (as returned
// by jsonschema.ValidationError.InstanceLocation) into RFC 6901 JSON
// Pointer form, e.g. []string{"dispatches", "2", "status"} -> "/dispatches/2/status".
func jsonPointerFromSegments(segments []string) string {
	if len(segments) == 0 {
		return ""
	}
	replacer := strings.NewReplacer("~", "~0", "/", "~1")
	var b strings.Builder
	for _, seg := range segments {
		b.WriteByte('/')
		b.WriteString(replacer.Replace(seg))
	}
	return b.String()
}

// resolveContractViolationWorker resolves the worker name a violation
// belongs to when its instance location falls under /dispatches/<n>,
// /results/<n>, or /workers/<n> — indexing that array in raw and reading
// its name, falling back to ant_name, then to "#<index>".
func resolveContractViolationWorker(raw any, segments []string) string {
	if len(segments) < 2 {
		return ""
	}

	arrayKey := segments[0]
	switch arrayKey {
	case "dispatches", "results", "workers":
	default:
		return ""
	}

	idx, err := strconv.Atoi(segments[1])
	if err != nil || idx < 0 {
		return ""
	}

	root, ok := raw.(map[string]any)
	if !ok {
		return ""
	}
	arr, ok := root[arrayKey].([]any)
	if !ok || idx >= len(arr) {
		return ""
	}

	fallback := fmt.Sprintf("#%d", idx)
	entry, ok := arr[idx].(map[string]any)
	if !ok {
		return fallback
	}
	if name, ok := entry["name"].(string); ok && strings.TrimSpace(name) != "" {
		return name
	}
	if antName, ok := entry["ant_name"].(string); ok && strings.TrimSpace(antName) != "" {
		return antName
	}
	return fallback
}

// contractSchemaCmd is the `aether contract-schema` command: `--check`
// (default) regenerates the schema in memory and byte-compares it against
// the committed file, exiting non-zero on drift without writing anything;
// `--write` regenerates and writes the committed file.
var contractSchemaCmd = &cobra.Command{
	Use:   "contract-schema",
	Short: "Generate or verify the completion-packet JSON Schema against the Go structs",
	Args:  cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		write, _ := cmd.Flags().GetBool("write")
		check, _ := cmd.Flags().GetBool("check")
		if write && check {
			err := fmt.Errorf("--write and --check are mutually exclusive")
			outputError(1, err.Error(), nil)
			return err
		}

		root, err := contractSchemaRepoRoot()
		if err != nil {
			outputError(1, err.Error(), nil)
			return err
		}

		generated, err := generateCompletionPacketSchemaBytes()
		if err != nil {
			outputError(1, fmt.Sprintf("failed to generate completion-packet schema: %v", err), nil)
			return err
		}

		schemaPath := filepath.Join(root, completionPacketSchemaRel)

		if write {
			if err := os.MkdirAll(filepath.Dir(schemaPath), 0o755); err != nil {
				outputError(1, fmt.Sprintf("failed to create schema directory: %v", err), nil)
				return err
			}
			if err := os.WriteFile(schemaPath, generated, 0o644); err != nil {
				outputError(1, fmt.Sprintf("failed to write completion-packet schema: %v", err), nil)
				return err
			}
			outputOK(map[string]interface{}{
				"written": completionPacketSchemaRel,
			})
			return nil
		}

		// --check (default): read-only. Must never write, per CLAUDE.md's
		// Definition of Done corollary against dry-run modes that mutate.
		committed, readErr := os.ReadFile(schemaPath)
		if readErr != nil {
			err := fmt.Errorf("failed to read committed completion-packet schema at %s: %w", completionPacketSchemaRel, readErr)
			outputError(1, err.Error(), map[string]interface{}{
				"path": completionPacketSchemaRel,
			})
			return err
		}

		if bytes.Equal(generated, committed) {
			outputOK(map[string]interface{}{
				"drift": false,
				"path":  completionPacketSchemaRel,
			})
			return nil
		}

		firstDiffLine := firstDifferingLine(generated, committed)
		err = fmt.Errorf("completion-packet schema drift detected: %s no longer matches the Go structs (first differing line: %d); regenerate with `aether contract-schema --write`", completionPacketSchemaRel, firstDiffLine)
		outputError(1, err.Error(), map[string]interface{}{
			"path":                 completionPacketSchemaRel,
			"first_differing_line": firstDiffLine,
			"regenerate_command":   "aether contract-schema --write",
		})
		return err
	},
}

// contractSchemaRepoRoot resolves the Aether module root from the current
// working directory.
func contractSchemaRepoRoot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("failed to resolve working directory: %w", err)
	}
	root := findAetherModuleRoot(cwd)
	if root == "" {
		return "", fmt.Errorf("failed to locate Aether module root from %s", cwd)
	}
	return root, nil
}

// firstDifferingLine returns the 1-indexed line number of the first line
// that differs between generated and committed, or 0 if one is a strict
// prefix of the other with no differing content up to the shorter length.
func firstDifferingLine(generated, committed []byte) int {
	genLines := strings.Split(string(generated), "\n")
	committedLines := strings.Split(string(committed), "\n")
	max := len(genLines)
	if len(committedLines) > max {
		max = len(committedLines)
	}
	for i := 0; i < max; i++ {
		var g, c string
		if i < len(genLines) {
			g = genLines[i]
		}
		if i < len(committedLines) {
			c = committedLines[i]
		}
		if g != c {
			return i + 1
		}
	}
	return 0
}

func init() {
	contractSchemaCmd.Flags().Bool("check", false, "Regenerate in memory and compare against the committed schema (default; read-only)")
	contractSchemaCmd.Flags().Bool("write", false, "Regenerate and write the committed completion-packet schema file")
	rootCmd.AddCommand(contractSchemaCmd)
}
