package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/calcosmic/Aether/pkg/colony"
)

// phaseResearchTemplateMarker identifies research files generated by the
// finalize fallback template rather than a research worker. Template files may
// be re-researched on the next plan run; worker-authored files are kept.
const phaseResearchTemplateMarker = "no dedicated research worker ran for this phase"

// phaseResearchStage is the dispatch stage for per-phase research Scouts.
const phaseResearchStage = "phase_research"

type phaseResearchCandidate struct {
	ID          int
	Name        string
	Description string
}

// phaseResearchCandidates returns the phases available for domain research at
// plan-only time. Phases come from the previous iteration's plan draft when
// the planning loop is underway, or from the active colony plan on a refresh.
// A fresh colony's first iteration has no phases yet — research dispatches
// begin on iteration 2, once the Route-Setter has drafted the route.
func phaseResearchCandidates(state colony.ColonyState, seed codexPlanIterationState) []phaseResearchCandidate {
	if seed.PreviousPlanDraft != nil && len(seed.PreviousPlanDraft.Phases) > 0 {
		candidates := make([]phaseResearchCandidate, 0, len(seed.PreviousPlanDraft.Phases))
		for i, phase := range seed.PreviousPlanDraft.Phases {
			candidates = append(candidates, phaseResearchCandidate{
				ID:          i + 1,
				Name:        strings.TrimSpace(phase.Name),
				Description: strings.TrimSpace(phase.Description),
			})
		}
		return candidates
	}
	candidates := make([]phaseResearchCandidate, 0, len(state.Plan.Phases))
	for _, phase := range state.Plan.Phases {
		if phase.ID <= 0 {
			continue
		}
		candidates = append(candidates, phaseResearchCandidate{
			ID:          phase.ID,
			Name:        strings.TrimSpace(phase.Name),
			Description: strings.TrimSpace(phase.Description),
		})
	}
	return candidates
}

// plannedPhaseResearchDispatches emits one phase_research Scout per candidate
// phase. Two rules govern which candidates get dispatched:
//  1. Within a single plan run's iterations (reresearch=false), a phase that
//     already has worker-authored research on disk is skipped — research runs
//     once per phase, not once per iteration.
//  2. On the first iteration of a replan (reresearch=true), the skip is
//     lifted and every candidate is re-dispatched from scratch — stale
//     findings from a prior run are never silently reused. The worker's
//     Outputs entry stays the plain phase-N-research.md filename; findings
//     overwrite the existing file in place, no timestamped archive sibling.
//
// The fast preset skips research entirely regardless of reresearch — speed is
// its contract.
func plannedPhaseResearchDispatches(root, planDepth, goal string, candidates []phaseResearchCandidate, survey codexSurveyContext, reresearch bool) []codexPlanningDispatch {
	if planDepth == "fast" || len(candidates) == 0 {
		return nil
	}
	dispatches := make([]codexPlanningDispatch, 0, len(candidates))
	for _, candidate := range candidates {
		fileName := fmt.Sprintf("phase-%d-research.md", candidate.ID)
		existingPath := filepath.Join(root, ".aether", "data", "phase-research", fileName)
		if !reresearch && hasWorkerAuthoredResearch(existingPath) {
			continue
		}
		// Wave 1: research runs parallel with the base Scout, BEFORE the
		// Route-Setter — research informs the route, not the postmortem.
		dispatches = append(dispatches, codexPlanningDispatch{
			Stage:     phaseResearchStage,
			Wave:      1,
			Caste:     "scout",
			AgentName: "aether-scout",
			Name:      deterministicAntName("scout", fmt.Sprintf("%s|plan-research|phase-%d", root, candidate.ID)),
			Task:      fmt.Sprintf("Research domain knowledge for phase %d: %s", candidate.ID, firstNonEmpty(candidate.Name, "unnamed phase")),
			TaskID:    fmt.Sprintf("plan-research-phase-%d", candidate.ID),
			Outputs:   []string{fileName},
			Status:    "planned",
			Brief:     renderPhaseResearchBrief(goal, candidate, survey),
		})
	}
	attachPlanningDispatchSkillAssignments(dispatches)
	return dispatches
}

// hasWorkerAuthoredResearch reports whether real (non-template) research
// already exists for a phase. Template files carry the fallback marker and are
// eligible for replacement by a research worker.
func hasWorkerAuthoredResearch(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return !strings.Contains(string(data), phaseResearchTemplateMarker)
}

// renderPhaseResearchBrief is the v5 Phase Domain Research mission, rebuilt on
// the modern engine: the Scout investigates one phase's domain and writes a
// six-section RESEARCH.md the planner and build briefs both consume.
func renderPhaseResearchBrief(goal string, candidate phaseResearchCandidate, survey codexSurveyContext) string {
	var b strings.Builder
	b.WriteString("You are a Scout performing Phase Domain Research.\n\n")
	b.WriteString("## Mission\n")
	b.WriteString(fmt.Sprintf("Investigate the domain knowledge needed for Phase %d: %s\n", candidate.ID, firstNonEmpty(candidate.Name, "unnamed phase")))
	b.WriteString(fmt.Sprintf("Colony goal: %s\n", strings.TrimSpace(goal)))
	if candidate.Description != "" {
		b.WriteString(fmt.Sprintf("Phase description: %s\n", candidate.Description))
	}
	b.WriteString("\n## Territory Survey\n")
	b.WriteString(renderPhaseResearchSurveySection(survey))
	b.WriteString("\n## Research Areas\n")
	b.WriteString("1. Key patterns in the existing codebase relevant to this phase\n")
	b.WriteString("2. External library/API documentation if the phase involves external tools\n")
	b.WriteString("3. Common gotchas and pitfalls in this domain\n")
	b.WriteString("4. Recommended implementation approach based on findings\n")
	b.WriteString("\n## Scope Constraints\n")
	b.WriteString("- Maximum 5 key patterns, maximum 3 gotchas, one recommended-approach paragraph\n")
	b.WriteString("- Total output under 3000 words; prioritize actionable guidance over exhaustive documentation\n")
	b.WriteString("- Cite a file path or URL for every pattern and gotcha\n")
	b.WriteString("\n## Output\n")
	b.WriteString(fmt.Sprintf("Write your findings to `.aether/data/phase-research/phase-%d-research.md` with exactly these six sections:\n\n", candidate.ID))
	b.WriteString(fmt.Sprintf("```markdown\n# Phase %d Research: %s\n\n", candidate.ID, firstNonEmpty(candidate.Name, "unnamed phase")))
	b.WriteString("**Generated:** {ISO-8601 timestamp}\n")
	b.WriteString(fmt.Sprintf("**Phase:** %d - %s\n", candidate.ID, firstNonEmpty(candidate.Name, "unnamed phase")))
	b.WriteString("**Research scope:** {one line on what was investigated}\n\n")
	b.WriteString("## Hive Wisdom (Pre-existing Knowledge)\n{relevant prior wisdom, or \"No relevant hive wisdom found\"}\n\n")
	b.WriteString("## Key Patterns\n{**pattern:** relevance (Source: path or URL)}\n\n")
	b.WriteString("## External Context\n{**topic:** finding (Source: URL), or \"No external research needed for this phase\"}\n\n")
	b.WriteString("## Gotchas\n{**issue:** prevention (Source: evidence)}\n\n")
	b.WriteString("## Recommended Approach\n{one synthesis paragraph}\n\n")
	b.WriteString("## Files to Study\n{bullet list of file paths}\n```\n")
	return b.String()
}

// renderPhaseResearchSurveySection mirrors the survey-injection shape
// renderPlanningWorkerBrief uses (cmd/codex_plan.go), so the research Scout
// and the planning workers see the same territory-survey framing. Never
// returns an empty string — a zero-value survey renders the explicit
// fallback sentence instead of an empty section.
func renderPhaseResearchSurveySection(survey codexSurveyContext) string {
	surveyDir := filepath.ToSlash(filepath.Join(".aether", "data", "survey"))
	surveyDocs := make([]string, 0, len(survey.SurveyDocs))
	for _, name := range survey.SurveyDocs {
		surveyDocs = append(surveyDocs, filepath.ToSlash(filepath.Join(surveyDir, name)))
	}
	if len(surveyDocs) == 0 && len(survey.Languages) == 0 && len(survey.Frameworks) == 0 && len(survey.Dependencies) == 0 {
		return "No territory survey available — scan the repository directly.\n"
	}
	var b strings.Builder
	b.WriteString("Primary survey source: ")
	b.WriteString(surveyDir)
	b.WriteString("\n")
	if len(surveyDocs) > 0 {
		b.WriteString("Survey docs to read first: ")
		b.WriteString(strings.Join(surveyDocs, ", "))
		b.WriteString("\n")
	}
	mapped := make([]string, 0, 3)
	if len(survey.Languages) > 0 {
		mapped = append(mapped, "languages: "+strings.Join(survey.Languages, ", "))
	}
	if len(survey.Frameworks) > 0 {
		mapped = append(mapped, "frameworks: "+strings.Join(survey.Frameworks, ", "))
	}
	if len(survey.Dependencies) > 0 {
		mapped = append(mapped, "dependencies: "+strings.Join(survey.Dependencies, ", "))
	}
	if len(mapped) > 0 {
		b.WriteString("Already-mapped territory: ")
		b.WriteString(strings.Join(mapped, "; "))
		b.WriteString(". Findings about already-mapped territory add no value — spend the research budget on what the survey does not cover.\n")
	}
	return b.String()
}

// phaseResearchBriefBudgetChars bounds how much phase research a build brief
// carries. Research is task content, not scaffolding, so the budget is
// generous — but a runaway file must not drown the assignment.
const phaseResearchBriefBudgetChars = 3500

// resolvePhaseResearchSection reads the phase's RESEARCH.md and renders it as
// a build-brief section. Returns "" when no research exists. Content over
// budget is truncated at a paragraph boundary with a pointer to the full file.
func resolvePhaseResearchSection(root string, phaseID int) string {
	if phaseID <= 0 {
		return ""
	}
	fileName := fmt.Sprintf("phase-%d-research.md", phaseID)
	data, err := os.ReadFile(filepath.Join(root, ".aether", "data", "phase-research", fileName))
	if err != nil {
		return ""
	}
	content := strings.TrimSpace(string(data))
	if content == "" {
		return ""
	}
	if len(content) > phaseResearchBriefBudgetChars {
		cut := content[:phaseResearchBriefBudgetChars]
		if idx := strings.LastIndex(cut, "\n\n"); idx > phaseResearchBriefBudgetChars/2 {
			cut = cut[:idx]
		}
		content = cut + fmt.Sprintf("\n\n_(truncated — full research: .aether/data/phase-research/%s)_", fileName)
	}
	var b strings.Builder
	b.WriteString("## Phase Research\n\n")
	b.WriteString(content)
	return b.String()
}
